# Generated by Django 4.0.6 on 2022-07-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='nifleur.school', verbose_name='Ecole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speaker_company_type', to='nifleur.companytype', verbose_name='Type de la compagnie'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='highest_degree',
            field=models.CharField(max_length=255, null=True, verbose_name='Diplôme le plus élevé'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='main_area_of_expertise',
            field=models.CharField(max_length=255, null=True, verbose_name='Domaine de compétence principal'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='professional_expertise_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Expert')], null=True, verbose_name="Niveau d'expertise en matière professionnelle"),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='teaching_expertise_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Expert')], null=True, verbose_name="Niveau d'expertise en pédagogie"),
        ),
    ]
