# Generated by Django 4.0.4 on 2022-07-08 14:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='company',
            name='relation_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='mail de la relation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='relation_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone de la relation'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='recruitmenttype',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='structurecampus',
            name='label',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
