# Generated by Django 4.0.6 on 2022-07-13 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_request_company', to='nifleur.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_request_school', to='nifleur.school', verbose_name='Ecole'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_year', to='nifleur.school', verbose_name='Ecole'),
        ),
    ]
