# Generated by Django 4.0.4 on 2022-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='structurecampus',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet'),
        ),
    ]
