# Generated by Django 4.0.4 on 2022-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.CharField(help_text='ex: M1', max_length=15, verbose_name='Année'),
        ),
    ]
