# Generated by Django 4.0.6 on 2022-07-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0002_discipline_school_alter_company_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='nifleur.schoolyear', verbose_name='Classe'),
        ),
    ]
