# Generated by Django 4.0.4 on 2022-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0002_alter_schoolyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='société'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='company_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Micro-entreprise'), (2, 'société'), (3, 'Profession libérale'), (4, 'Portage salariale')], null=True, verbose_name='Type de la société'),
        ),
    ]
