# Generated by Django 4.0.4 on 2022-06-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0003_alter_schoolyear_structure_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_year', to='nifleur.schoolyear', verbose_name='Classe'),
        ),
    ]
