# Generated by Django 4.0.4 on 2022-06-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifleur', '0004_discipline_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='speaker',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='discipline', to='nifleur.speaker', verbose_name='Intervenant'),
        ),
    ]
